FROM node:20-alpine
WORKDIR /var/www/auth
RUN corepack enable && corepack prepare pnpm@latest --activate
ENV CI=true
COPY package.json pnpm-lock.yaml* ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm nx build auth
EXPOSE 8000
CMD ["node", "./dist/apps/auth/main.js"]